version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    commit-message:
      prefix: deps

  - package-ecosystem: "github-actions"
    directory: "/templates"
    schedule:
      interval: "daily"
    commit-message:
      prefix: deps
