name: Release

on:

  push:

    branches:
      - main

jobs:

  release-please:

    name: Run release-please
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:

      - name: Run Release Please
        uses: google-github-actions/release-please-action@ca6063f4ed81b55db15b8c42d1b6f7925866342d # v3.7.11
        id: r
        with:
          release-type: simple
          package-name: reusable-terraform-plan-apply
          changelog-types: >
            [
              {"type": "deps", "section": "Dependency Updates", "hidden": false},
              {"type": "feat", "section": "Features", "hidden": false},
              {"type": "fix", "section": "Bug Fixes", "hidden": false}
            ]
