name: Release

on:

  push:

    branches:
      - main

    paths:
      - ".github/workflows/reusable-terraform-plan-apply.yml"

jobs:

  release-please:

    name: Run release-please
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:

      - name: Run Release Please
        uses: google-github-actions/release-please-action@51ee8ae2605bd5ce1cfdcc5938684908f1cd9f69 # v3.7.9
        id: r
        with:
          release-type: simple
          package-name: reusable-terraform-plan-apply
